### ISSUE TITLE
##參考同學計算圓面積程式練習

### ISSUE THREAD

**Issue by Rola0605** [roberthsu2003/__2024_05_05_sunday__#9]
### 參考同學計算圓面積程式練習

```
pi = 3.14
r = 2
area =(pi*r*r)
print ( " 圓面積:",area)
```

_Originally posted by @Rola0605 in https://github.com/roberthsu2003/__2024_05_05_sunday__/issues/8#issuecomment-2094700933_

**Comment by thunder114069** [comment]
from cmath import pi
R=10
area=(pi*(R**2)/2)
print("圓面積為",area)

@thunder114069 ➜ /workspaces/2024-05-05-1- (main) $ /usr/local/bin/python /workspaces/2024-05-05-1-/thunder/5-5.py
圓面積為 157.07963267948966
